---
title: "R Notebook"
output: html_notebook
---

Practices through the "Bayes Rules!"
(https://www.bayesrulesbook.com/chapter-2.html)
I changed the place of the file. Is it still working?
It seems like it is still working.

```{r}
# Load packages
install.packages("bayesrules")
install.packages("janitor")
```


```{r}
library(bayesrules)
library(tidyverse)
library(janitor)
```


```{r}
# Import article data
data(fake_news)
str(fake_news)
names(fake_news)
##

fake_news %>%
  tabyl(type) %>%
  adorn_totals("row")

fake_news %>%
  tabyl(title_has_excl, type) %>%
  adorn_totals("row")
```


```{r}
article <- data.frame(type = c("real", "fake"))
prior <- c(0.6, 0.4)

sample_n(article, size = 3, weight = prior, replace = TRUE)

```
```{r}
set.seed(84735)
sample_n(article, size = 3, weight = prior, replace = TRUE)

article_sim <- sample_n(article, size = 10000, weight = prior, replace = TRUE)

ggplot(article_sim, aes(x = type)) +
  geom_bar()

```

```{r}
article_sim %>%
  tabyl(type) %>%
  adorn_totals("row")

```

```{r}
article_sim <- article_sim %>%
  mutate(data_model = case_when(type == "fake" ~ 0.2667,
                                type == "real" ~ 0.0222))

glimpse(article_sim)
```


#### Really interesting way to conduct the simulation
```{r}
data <- c("no", "yes")

set.seed(3)
article_sim <- article_sim %>%
  group_by(1:n()) %>% # exclamation point performed separately for each 10000
  mutate(usage = sample(data, size = 1, prob = c(1- data_model, data_model)))

```


```{r}
article_sim %>%
  tabyl(usage, type) %>%
  adorn_totals(c("col","row"))
```

Below is the posterior probability

```{r}
article_sim %>%
  filter(usage == "yes") %>%
  tabyl(type) %>%
  adorn_totals("row")
```

